@CATodos.Api_HostAddress = https://localhost:7155
GET {{CATodos.Api_HostAddress}}/categorie
Accept: text/csv


###

GET {{CATodos.Api_HostAddress}}/categorie/42


###

GET {{CATodos.Api_HostAddress}}/todo
CAAccessKey: DAFB248C-9B37-45D4-AFD3-A99BA386BF29
#CAAccessKey: D8364D9F-07BC-4060-AE22-9AA0284F690F

###

GET {{CATodos.Api_HostAddress}}/todo?q=faire

###
GET {{CATodos.Api_HostAddress}}/todo/12

###
GET {{CATodos.Api_HostAddress}}/todo/400

###
Delete {{CATodos.Api_HostAddress}}/todo/2
CAAccessKey: D8364D9F-07BC-4060-AE22-9AA0284F690F

###

POST {{CATodos.Api_HostAddress}}/todo
Content-Type: application/json
CAAccessKey: DAFB248C-9B37-45D4-AFD3-A99BA386BF29


{
  "title": "test 1",
  "dueDate": "2024-05-10",
  "latitude": 39,
  "longitude": -1
}

###

PUT {{CATodos.Api_HostAddress}}/todo/22
Content-Type: application/json

{
  "title": "test 1",
  "dueDate": "2024-05-10",
  "latitude": 39,
  "longitude": -1,
  "Categories": [6]
}

###

PATCH {{CATodos.Api_HostAddress}}/todo/5
Content-Type: application/json

{
  "Done": false
}

###
